### ISSUE TITLE
Problem when reload page

### ISSUE THREAD

**Issue by RmpNathan** [TheUltrasoft/Parallaxie#2]
Hi, thx for your parallax library, everything works well except on one page, when i'm on the parallax and reload the page, the parallax image is cut and if i scroll just 1px the image appears
If you have a solution :)

**Comment by RmpNathan** [comment]
when i reload : 
![parallax-reload](https://user-images.githubusercontent.com/19663838/66484666-b21a0b00-eaa7-11e9-847a-b90b43d6625d.png)
when i scroll 1px :
![parallaxe-bon](https://user-images.githubusercontent.com/19663838/66484701-c958f880-eaa7-11e9-85ec-df66c39f9c68.png)

**Comment by sptutusukanta** [comment]
Hi, @RmpNathan it might be a bug. I will fix it soon. :)
By the way, can you share any public URL where this happens?

**Comment by RmpNathan** [comment]
thx :)
